spring.application.name=ChatService

server.port=${PORT:8080}

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL:gemma3:1b}

#spring.application.name=ChatService

#spring.ai.ollama.base-url=http://ollama:11434
#spring.ai.ollama.chat.options.model=gemma3:1b
